[keycloak]
keycloak_url="https://user.kosmos.test.io/auth/realms/kosmos/protocol/openid-connect/token"
keycloak_username="edge-user"
keycloak_pw="test-pw"
keycloak_client="kosmos-global"
keycloak_secret="kosmos-secret"

[Harbor]
host="harbor.test.io/"
user="robot$edge-pull"
password="testpw"


[KOSMoS_Global]
host="https://kosmos-global.org"
user=""
password=""
schema_pull_frequency=120
contract_check_frequency=10
contract_publish_frequency=30
local_contract_file_path="tests/test_files/sw-prod.json"

[MQTT]
host="mqtt-broker.kosmos-local"
port=1883
keepalive=60
user=""
password=""
blockchain_topic=""
analysis_topic=""
new_contract_instance_topic="Vertragsmanagement/neuerVertrag"
environment='PORT=1883#TOPIC=kosmos/machine-data/9d82699b-373a-4b2a-8925-f7bfacb618a4/Sensor/tbd/Update#MQTT_BROKER_FQDN=172.18.0.4#PAYLOAD={"customerId": "datarella","prodMinutes": 0,"prodPieces": 0,"toolChanges": 0,"travelDistance": 0,"directionChange": 0,"materialType": "aluminum"}'
command="echo 123 | tee foobar"

[database]
user="kosmos_local"
database="kosmos_contracts"
password="db_pass"
host="postgres.kosmos-local"
port=5432
