name: Lint and test
on: push

jobs:
  yamllint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        uses: actions/setup-go@v3
        with:
          go-version: "1.17"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

          args: --timeout=10m

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: "1.17"
          check-latest: true

      - name: Run unit tests
        run: |
          go get -u github.com/jstemmer/go-junit-report
          go test ./... -coverprofile unit-test.out -race --tags unit | go-junit-report > report.xml

      - name: Upload JUnit report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.xml
          retention-days: 1
